--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: birthday
DROP TABLE IF EXISTS birthday;
CREATE TABLE birthday (id INTEGER PRIMARY KEY AUTOINCREMENT, chatId VARCHAR (9) NOT NULL REFERENCES ids (id), date DATETIME (10) NOT NULL, name VARCHAR NOT NULL);

-- Table: ids
DROP TABLE IF EXISTS ids;
CREATE TABLE ids (id INTEGER PRIMARY KEY AUTOINCREMENT, uid VARCHAR (9) NOT NULL UNIQUE);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
